Update spark_data_source.py with configuration param
sodadata/soda-core pull request #1884
Opened 2023-06-05 09:18 UTC by Clusiv

Added param 'configuration' to support additional spark configurations like 'spark.executor.memory':'512m'

2023-07-03 09:51 UTC, vijaykiran commented on soda/spark/soda/data_sources/spark_data_source.py
> +        configuration=configuration,
Can you please use `kwargs` instead? Otherwise it will break other connection functions

2023-07-03 09:52 UTC, vijaykiran requested changes
Please see my comment about kwarts ...

2023-11-03 14:47 UTC, m1n0 commented
hi @Clusiv , could you please do the requested changes from above please?

2025-03-12 10:08 UTC, m1n0 commented
Indeed @Rhiyo , thanks for pointing that out, closing

2025-03-12 10:08 UTC, closed without merging