Feature/adding more file formats for duckdb
sodadata/soda-core pull request #1942
Opened 2023-10-02 11:57 UTC by PaoloLeonard

Adding support for csv, parquet and json file in Soda-core for the duckdb engine.

2023-10-02 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/sodadata/soda-core?pullRequest=1942) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/sodadata/soda-core?pullRequest=1942) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/sodadata/soda-core?pullRequest=1942) it.</sub>

2023-10-04 21:22 UTC, m1n0 requested changes
Thanks for the contribution! I added a small suggestion otherwise this LGTM!

2023-10-04 21:22 UTC, m1n0 commented on soda/duckdb/tests/test_duckdb.py
> +        f"""
Can we remove the f-strings as there are no vars in the string and code analysis is complaining?

```suggestion
        """
```

2023-10-04 21:22 UTC, m1n0 commented on soda/duckdb/tests/test_duckdb.py
> +        f"""
```suggestion
        """
```

2023-10-04 21:22 UTC, m1n0 commented on soda/duckdb/tests/test_duckdb.py
> +        f"""
```suggestion
        """
```

2023-10-05 06:16 UTC, PaoloLeonard commented
> Thanks for the contribution! I added a small suggestion otherwise this LGTM!

Thanks for the suggestions, applied!

2023-10-06 16:04 UTC, m1n0 approved these changes

2023-10-06 16:05 UTC, merged